COMMENT ON TABLE osm.building_polygon IS 'OpenStreetMap building polygons - all polygons with a building tag.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/building.lua';
COMMENT ON TABLE osm.building_point IS 'OpenStreetMap building points - all points with a building tag.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/building.lua';

COMMENT ON COLUMN osm.building_polygon.height IS 'Building height.  Should be in meters (m) but is not enforced.  Please fix data in OpenStreetMap.org if incorrect values are discovered.';
COMMENT ON COLUMN osm.building_point.height IS 'Building height.  Should be in meters (m) but is not enforced.  Please fix data in OpenStreetMap.org if incorrect values are discovered.';

COMMENT ON COLUMN osm.building_polygon.levels IS 'Number (#) of levels in the building.';
COMMENT ON COLUMN osm.building_point.levels IS 'Number (#) of levels in the building.';
COMMENT ON COLUMN osm.building_polygon.wheelchair IS 'Indicates if building is wheelchair accessible.';
COMMENT ON COLUMN osm.building_point.wheelchair IS 'Indicates if building is wheelchair accessible.';


ALTER TABLE osm.building_polygon
    ADD CONSTRAINT pk_osm_building_polygon_osm_id
    PRIMARY KEY (osm_id)
;

CREATE INDEX ix_osm_building_polygon_type ON osm.building_polygon (osm_type);


CREATE VIEW osm.vbuilding_all AS
SELECT osm_id, 'N' AS geom_type, name, levels, height, operator, wheelchair,
        COALESCE(housenumber, '')
        || COALESCE(' ' || street, '')
        || COALESCE(', ' || city || ' ', '')
        || COALESCE(', ' || state || ' ', '')
            AS address,
        geom
    FROM osm.building_point
UNION
SELECT osm_id, 'W' AS geom_type, name, levels, height, operator, wheelchair,
        COALESCE(housenumber, '')
        || COALESCE(' ' || street, '')
        || COALESCE(', ' || city || ' ', '')
        || COALESCE(', ' || state || ' ', '')
            AS address,
        ST_Centroid(geom) AS geom
    FROM osm.building_polygon
;

COMMENT ON VIEW osm.vbuilding_all IS 'Converts polygon buildings to point with ST_Centroid(), combines with source points using UNION.';
COMMENT ON COLUMN osm.vbuilding_all.address IS 'Simple attempt to combine address parts into single column with COALESCE.';
