COMMENT ON TABLE osm.building_polygon IS 'OpenStreetMap buildings - all polygons with a building tag.  Generated by osm2pgsql Flex output using pgosm/flex-config/building.lua';

ALTER TABLE osm.building_polygon
    ADD CONSTRAINT pk_osm_building_polygon_osm_id
    PRIMARY KEY (osm_id)
;

CREATE INDEX ix_osm_building_polygon_type ON osm.building_polygon (osm_type);
