COMMENT ON TABLE osm.infrastructure_point IS 'OpenStreetMap infrastructure layer.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/infrasturcture.lua';
COMMENT ON COLUMN osm.infrastructure_point.osm_type IS '.';


ALTER TABLE osm.infrastructure_point
	ADD CONSTRAINT pk_osm_infrastructure_point_osm_id
    PRIMARY KEY (osm_id)
;

CREATE INDEX ix_osm_infrastructure_point_highway ON osm.infrastructure_point (osm_type);

COMMENT ON COLUMN osm.infrastructure_point.osm_id IS 'OpenStreetMap ID. Unique along with geometry type.';
COMMENT ON COLUMN osm.infrastructure_point.ele IS 'Elevation in meters';
