COMMENT ON TABLE osm.leisure_polygon IS 'OpenStreetMap leisure polygons - all polygons with a leisure tag.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/leisure.lua';
COMMENT ON TABLE osm.leisure_point IS 'OpenStreetMap leisure points - all points with a leisure tag.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/leisure.lua';


ALTER TABLE osm.leisure_point
    ADD CONSTRAINT pk_osm_leisure_point_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE osm.leisure_polygon
    ADD CONSTRAINT pk_osm_leisure_polygon_osm_id
    PRIMARY KEY (osm_id)
;

CREATE INDEX ix_osm_leisure_point_type ON osm.leisure_point (osm_type);
CREATE INDEX ix_osm_leisure_polygon_type ON osm.leisure_polygon (osm_type);
