COMMENT ON TABLE osm.natural_point IS 'OpenStreetMap natural points, e.g. trees, peaks, etc..  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';
COMMENT ON TABLE osm.natural_line IS 'OpenStreetMap natural lines, e.g. cliffs, tree row, etc.. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';
COMMENT ON TABLE osm.natural_polygon IS 'OpenStreetMap natural polygons, e.g. woods, grass, etc.. Generated by osm2pgsql Flex output using pgosm-flex/flex-config/natural.lua';

COMMENT ON COLUMN osm.natural_point.ele IS 'Elevation in meters';
COMMENT ON COLUMN osm.natural_line.ele IS 'Elevation in meters';
COMMENT ON COLUMN osm.natural_polygon.ele IS 'Elevation in meters';

ALTER TABLE osm.natural_point
    ADD CONSTRAINT pk_osm_natural_point_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE osm.natural_line
    ADD CONSTRAINT pk_osm_natural_line_osm_id
    PRIMARY KEY (osm_id)
;
ALTER TABLE osm.natural_polygon
    ADD CONSTRAINT pk_osm_natural_polygon_osm_id
    PRIMARY KEY (osm_id)
;


CREATE INDEX ix_osm_natural_point_type ON osm.natural_point (osm_type);
CREATE INDEX ix_osm_natural_line_type ON osm.natural_line (osm_type);
CREATE INDEX ix_osm_natural_polygon_type ON osm.natural_polygon (osm_type);


