COMMENT ON TABLE osm.natural_point IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/natural.lua';
COMMENT ON TABLE osm.natural_line IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/natural.lua';
COMMENT ON TABLE osm.natural_polygon IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/natural.lua';


ALTER TABLE osm.natural_point
    ADD CONSTRAINT pk_osm_natural_point_node_id
    PRIMARY KEY (node_id)
;
ALTER TABLE osm.natural_line
    ADD CONSTRAINT pk_osm_natural_line_way_id
    PRIMARY KEY (way_id)
;
ALTER TABLE osm.natural_polygon
    ADD CONSTRAINT pk_osm_natural_polygon_way_id
    PRIMARY KEY (way_id)
;


CREATE INDEX ix_osm_natural_point_type ON osm.natural_point (osm_type);
CREATE INDEX ix_osm_natural_line_type ON osm.natural_line (osm_type);
CREATE INDEX ix_osm_natural_polygon_type ON osm.natural_polygon (osm_type);


