COMMENT ON TABLE osm.road_line IS 'OpenStreetMap roads, full layer.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/road.lua';
COMMENT ON COLUMN osm.road_line.osm_type IS 'Value from "highway" key from OpenStreetMap data.  e.g. motorway, residential, service, footway, etc.';

COMMENT ON COLUMN osm.road_line.maxspeed IS 'Maximum posted speed limit in kilometers per hour (km/kr).  Units not enforced by OpenStreetMap.  Please fix values in MPH in OpenStreetMap.org to either the value in km/hr OR with the suffix "mph" so it can be properly converted.  See https://wiki.openstreetmap.org/wiki/Key:maxspeed';
COMMENT ON COLUMN osm.road_major.maxspeed IS 'Maximum posted speed limit in kilometers per hour (km/kr).  Units not enforced by OpenStreetMap.  Please fix values in MPH in OpenStreetMap.org to either the value in km/hr OR with the suffix "mph" so it can be properly converted.  See https://wiki.openstreetmap.org/wiki/Key:maxspeed';


ALTER TABLE osm.road_line
	ADD CONSTRAINT pk_osm_road_line_way_id
    PRIMARY KEY (way_id)
;


CREATE INDEX ix_osm_road_line_highway ON osm.road_line (osm_type);
