COMMENT ON TABLE osm.road_line IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/road.lua';
COMMENT ON COLUMN osm.road_line.osm_type IS 'Value from "highway" key from OpenStreetMap data.  e.g. motorway, residential, service, footway, etc.';

ALTER TABLE osm.road_line
	ADD CONSTRAINT pk_osm_road_line_way_id
    PRIMARY KEY (way_id)
;

CREATE INDEX ix_osm_road_line_highway ON osm.road_line (osm_type);
