\i sql/pgosm-meta.sql
\i sql/amenity.sql
\i sql/building.sql
\i sql/indoor.sql
\i sql/infrastructure.sql
\i sql/landuse.sql
\i sql/leisure.sql
\i sql/natural.sql
\i sql/traffic.sql
\i sql/place.sql
\i sql/poi.sql
\i sql/public_transport.sql
\i sql/road.sql
\i sql/shop.sql
\i sql/water.sql
