COMMENT ON TABLE osm.traffic_point IS 'OpenStreetMap traffic related points.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/traffic.lua';
COMMENT ON TABLE osm.traffic_line IS 'OpenStreetMap traffic related lines.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/traffic.lua';
COMMENT ON TABLE osm.traffic_polygon IS 'OpenStreetMap traffic related polygons.  Generated by osm2pgsql Flex output using pgosm-flex/flex-config/traffic.lua';


ALTER TABLE osm.traffic_point
    ADD CONSTRAINT pk_osm_traffic_point_osm_id
    PRIMARY KEY (osm_id)
;


CREATE INDEX ix_osm_traffic_point_type ON osm.traffic_point (osm_type);
