-- Deploy pgosm-flex:001 to pg

BEGIN;

CREATE SCHEMA pgosm;

CREATE TABLE pgosm.road
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region TEXT NOT NULL DEFAULT 'United States',
    osm_type TEXT NOT NULL,
    route_motor BOOLEAN DEFAULT True,
    route_foot BOOLEAN DEFAULT True,
    route_cycle BOOLEAN DEFAULT True,
    maxspeed NUMERIC(6,2) NOT NULL,
    maxspeed_mph NUMERIC(6,2) NOT NULL
        GENERATED ALWAYS AS (maxspeed / 1.609344
            ) STORED,
    CONSTRAINT uq_pgosm_routable_code UNIQUE (region, osm_type)
);


COMMENT ON TABLE pgosm.road IS 'Provides lookup information for road layers, generally related to routing use cases.';


COMMIT;
