
BEGIN;


CREATE TABLE IF NOT EXISTS {schema_name}.pgosm_flex (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    imported TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    osm_date TIMESTAMPTZ NOT NULL,
    region text NOT NULL,
    layerset TEXT NULL,
    srid text NOT NULL,
    pgosm_flex_version text NOT NULL,
    osm2pgsql_version text NOT NULL,
    "language" text NOT NULL,
    import_mode JSONB NULL,
    import_status TEXT NOT NULL DEFAULT 'Initializing',
    input_file TEXT NULL,
    CONSTRAINT pk_osm_pgosm_flex PRIMARY KEY (id)
);

ALTER TABLE {schema_name}.pgosm_flex
    DROP COLUMN IF EXISTS osm2pgsql_mode
;

ALTER TABLE {schema_name}.pgosm_flex
    DROP COLUMN IF EXISTS osm2pgsql_replication;

ALTER TABLE {schema_name}.pgosm_flex
    ADD COLUMN IF NOT EXISTS import_mode JSONB NULL;

ALTER TABLE {schema_name}.pgosm_flex
    DROP COLUMN IF EXISTS import_uuid;

ALTER TABLE {schema_name}.pgosm_flex
    ADD COLUMN IF NOT EXISTS import_status TEXT NOT NULL DEFAULT 'Initializing';

ALTER TABLE {schema_name}.pgosm_flex
    ADD COLUMN IF NOT EXISTS layerset TEXT NULL;

ALTER TABLE {schema_name}.pgosm_flex
    ADD COLUMN IF NOT EXISTS input_file TEXT NULL;

ALTER TABLE {schema_name}.pgosm_flex DROP COLUMN IF EXISTS project_url;
ALTER TABLE {schema_name}.pgosm_flex DROP COLUMN IF EXISTS default_date;

ALTER TABLE {schema_name}.pgosm_flex ALTER COLUMN osm_date TYPE TIMESTAMPTZ;

COMMENT ON TABLE {schema_name}.pgosm_flex IS 'Provides meta information on the PgOSM-Flex project including version and SRID used during the import. One row per import.';

COMMENT ON COLUMN {schema_name}.pgosm_flex.imported IS 'Indicates when the import was ran.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.osm_date IS 'Indicates the date of the OpenStreetMap data loaded. Uses timestamp from PBF file metadata when available.  If metadata not available this represents --osm-date at runtime, or the date of today in timezone based on computer running import.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.srid IS 'SRID of imported data.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.pgosm_flex_version IS 'Version of PgOSM-Flex used to generate schema.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.osm2pgsql_version IS 'Version of osm2pgsql used to load data.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.region IS 'Region specified at run time via --region and --subregion values.  When using --input-file without region/subregion, this defaults to the input filename.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.language IS 'Preferred language specified at run time via env var PGOSM_LANGUAGE.  Empty string when not defined.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.layerset IS 'PgOSM Flex layerset used for the import style.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.import_status IS 'Status of the import. Starts as initialized, tracks status during imports and final success/failure.';
COMMENT ON COLUMN {schema_name}.pgosm_flex.input_file IS 'Tracks explicit file defined when --input-file is used.  NULL when --input-file not used.';



COMMIT;
